---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rdp-kali
  labels:
    app: rdp-kali
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rdp-kali
  template:
    metadata:
      labels:
        app: rdp-kali
    spec:
      # Pod-level security context for sysctls
      securityContext:
        sysctls:
        - name: net.ipv6.conf.all.disable_ipv6
          value: "0"
      containers:
      - name: rdp-kali
        image: ghcr.io/trigus42/kali-rdp-container:latest
        imagePullPolicy: Always
        env:
        - name: SSHD_ENABLE
          value: "true"
        - name: MSF_ENABLE
          value: "true"
        - name: DIND_ENABLE
          value: "true"
        - name: HISTFILE
          value: "/workspace/host-volume/.persist/.zsh_history"
        - name: SYNCTHING_ENABLE
          value: "true"
        - name: STHOMEDIR
          value: "/workspace/host-volume/.persist/.syncthing"
        - name: SYNCTHING_SYNC_DIR
          value: "/workspace/host-volume/syncthing"
        ports:
        - containerPort: 3389
          name: rdp
        - containerPort: 22
          name: ssh
        # Container-level security context for privileges and capabilities
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
        volumeMounts:
        - name: host-workspace
          mountPath: /workspace/host-volume/
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"

      volumes:
      - name: host-workspace
        hostPath:
          path: /var/data/kali-workspace
          type: DirectoryOrCreate
