[supervisord]
nodaemon=true

[program:xrdp]
command=/startup/xrdp.sh
autostart=true
autorestart=true
user=root
priority=10

[program:sshd]
command=/startup/sshd.sh
autostart=true
autorestart=true
user=root
priority=20

[program:user-setup]
command=/startup/msf.sh
user=root
priority=10
startsecs=30