[supervisord]
nodaemon=true
user=root

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:xrdp]
command=/startup/xrdp.sh
autostart=true
autorestart=true
user=root
priority=10
stderr_logfile=/var/log/xrdp.err.log
stdout_logfile=/var/log/xrdp.out.log

[program:sshd]
command=/startup/sshd.sh
autostart=true
autorestart=true
user=root
priority=20
stderr_logfile=/var/log/sshd.err.log
stdout_logfile=/var/log/sshd.out.log

[program:dockerd]
command=/startup/docker.sh
user=root
priority=30
autostart=true
autorestart=true
exitcodes=0
startsecs=0
stderr_logfile=/var/log/dockerd.err.log
stdout_logfile=/var/log/dockerd.out.log

[program:metasploit]
command=/startup/msf.sh
user=root
priority=40
exitcodes=0
autorestart=false
startsecs=0
stderr_logfile=/var/log/msf.err.log
stdout_logfile=/var/log/msf.out.log