[supervisord]
nodaemon=true
user=root

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:env]
command=/startup/env.sh
user=root
priority=1
autostart=true
autorestart=false
exitcodes=0
startsecs=0
stderr_logfile=/var/log/env.err.log
stdout_logfile=/var/log/env.out.log

[program:xrdp]
command=/startup/xrdp.sh
autostart=true
autorestart=true
user=root
priority=10
stderr_logfile=/var/log/xrdp.err.log
stdout_logfile=/var/log/xrdp.out.log

[program:sshd]
command=/startup/sshd.sh
autostart=true
autorestart=true
user=root
priority=20
stderr_logfile=/var/log/sshd.err.log
stdout_logfile=/var/log/sshd.out.log

[program:gocryptfs]
command=/startup/gocryptfs.sh
user=root
priority=30
autostart=true
autorestart=true
stderr_logfile=/var/log/gocryptfs.err.log
stdout_logfile=/var/log/gocryptfs.out.log

[program:dockerd]
command=/startup/docker.sh
user=root
priority=40
autostart=true
autorestart=false
exitcodes=0
startsecs=0
stderr_logfile=/var/log/dockerd.err.log
stdout_logfile=/var/log/dockerd.out.log

[program:metasploit]
command=/startup/msf.sh
user=root
priority=50
exitcodes=0
autostart=true
autorestart=false
startsecs=0
exitcodes=0
stderr_logfile=/var/log/msf.err.log
stdout_logfile=/var/log/msf.out.log

[program:syncthing]
command=/startup/syncthing.sh
user=root
priority=60
autostart=true
autorestart=true
stderr_logfile=/var/log/syncthing.err.log
stdout_logfile=/var/log/syncthing.out.log